INSERT ALL 
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWBA', 'Bulawayo Airport', 'Bulawayo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWBU', 'Bulawayo', 'Bulawayo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWBW', 'Bulawayo Custom House', 'Bulawayo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWAGS', 'Aviation Ground Services', 'Harare')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWKC', 'Kurima Greater Hre', 'Harare')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWHR', 'Harare Custom House', 'Harare')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWKR', 'Kurima Region 1 Cash', 'Harare')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWHA', 'Harare Airport', 'Harare')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWHI', 'Harare International', 'Harare')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWNY', 'Nyamapanda Border ME', 'Mashonaland East')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWCY', 'Chinhoyi', 'Mashonaland East')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWCH', 'Chirundu Custom House', 'Mashonaland West')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWCN', 'Chinhoyi Custom House', 'Mashonaland West')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWKB', 'Kariba Border', 'Mashonaland West')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWMK', 'Mukumbura Border', 'Mashonaland Central')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWBI', 'Bindura', 'Mashonaland Central')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWKN', 'Kanyemba Border', 'Mashonaland Central')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWSN', 'Sango Border', 'Masvingo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWCI', 'Chiredzi', 'Masvingo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWCZ', 'Chiredzi Custom House', 'Masvingo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZMSV', 'MASVINGO', 'Masvingo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWMN', 'Masvingo Custom House', 'Masvingo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWBR', 'Buffalo Range', 'Masvingo')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWHW', 'Hwange Custom House', 'Matabeleland North')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZVFT', 'Victoria Falls', 'Matabeleland North')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWPM', 'Pandamatenga Border', 'Matabeleland North')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWHG', 'Hwange', 'Matabeleland North')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWVF', 'Victoria Falls Customs', 'Matabeleland North')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWKZ', 'Kazungula Border', 'Matabeleland North')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWMG', 'Maitengwe Border', 'Matabeleland South')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWPT', 'Plumtree Custom House', 'Matabeleland South')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWBB', 'Beitbridge Custom House', 'Matabeleland South')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWZS', 'Zvishavane Customs House', 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWZV', 'Zvishavane', 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWKW', 'Kwekwe Custom House', 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZKAD', 'KADOMA', 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWGW', 'Gweru Custom House', 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZKWE', 'KWEKWE', 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWKD', 'Kadoma Custom House', 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWGR', 'Gweru' , 'Midlands')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWFB', 'Forbes Border', 'Manicaland')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWMU', 'Mutare', 'Manicaland')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWMS', 'Mount Selinda Border', 'Manicaland')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWRU', 'Rusape', 'Manicaland')
    INTO office (OFFICE_CODE, OFFICE_NAME,province) values ('ZWCP', 'Chipinge', 'Manicaland')
    SELECT 1 FROM dual;